package kitaponeri;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import org.icepdf.ri.common.ComponentKeyBinding;
import org.icepdf.ri.common.SwingController;
import org.icepdf.ri.common.SwingViewBuilder;

public class IyiPopulerYeni extends javax.swing.JFrame {
    
    static String username;
    static ImageIcon icon1,icon2,icon3,icon4,icon5,icon6,icon7,icon8,icon9,icon10;
    static boolean ck1,ck2,ck3,ck4,ck5,ck6,ck7,ck8,ck9,ck10;
    static String books[] = new String[20];
    
    public IyiPopulerYeni(){
        initComponents();
    }
    
    public IyiPopulerYeni(String[] books, int a) throws MalformedURLException, IOException{
        for(int i = 0; i<10;i++){
            IyiPopulerYeni.books[i] = books[i];
        }
        
        icon1 = (new ImageIcon(ImageIO.read(new URL(books[0]))));
        icon2 = (new ImageIcon(ImageIO.read(new URL(books[1]))));
        icon3 = (new ImageIcon(ImageIO.read(new URL(books[2]))));
        icon4 = (new ImageIcon(ImageIO.read(new URL(books[3]))));
        icon5 = (new ImageIcon(ImageIO.read(new URL(books[4]))));
        
        
        
        initComponents();
        ph1.setText(books[5]); ph2.setText(books[6]); ph3.setText(books[7]);
        ph4.setText(books[8]); ph5.setText(books[9]);
        ph6.setVisible(false); ph7.setVisible(false);
        ph8.setVisible(false); ph9.setVisible(false); ph10.setVisible(false);
        
        
    }
    
    public IyiPopulerYeni(String[] books) throws MalformedURLException, IOException{
        for(int i = 0; i<20;i++){
            IyiPopulerYeni.books[i] = books[i];
        }
        
        icon1 = (new ImageIcon(ImageIO.read(new URL(books[0]))));
        icon2 = (new ImageIcon(ImageIO.read(new URL(books[1]))));
        icon3 = (new ImageIcon(ImageIO.read(new URL(books[2]))));
        icon4 = (new ImageIcon(ImageIO.read(new URL(books[3]))));
        icon5 = (new ImageIcon(ImageIO.read(new URL(books[4]))));
        icon6 = (new ImageIcon(ImageIO.read(new URL(books[5]))));
        icon7 = (new ImageIcon(ImageIO.read(new URL(books[6]))));
        icon8 = (new ImageIcon(ImageIO.read(new URL(books[7]))));
        icon9 = (new ImageIcon(ImageIO.read(new URL(books[8]))));
        icon10 = (new ImageIcon(ImageIO.read(new URL(books[9]))));
        
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ph1 = new javax.swing.JLabel();
        ph2 = new javax.swing.JLabel();
        ph4 = new javax.swing.JLabel();
        ph3 = new javax.swing.JLabel();
        ph7 = new javax.swing.JLabel();
        ph9 = new javax.swing.JLabel();
        ph8 = new javax.swing.JLabel();
        ph6 = new javax.swing.JLabel();
        ph5 = new javax.swing.JLabel();
        ph10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ph1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ph1.setIcon(icon1);
        ph1.setText(books[10]);
        ph1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ph1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ph1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ph1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ph1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ph1MouseClicked(evt);
            }
        });

        ph2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ph2.setIcon(icon2);
        ph2.setText(books[11]);
        ph2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ph2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ph2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ph2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ph2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ph2MouseClicked(evt);
            }
        });

        ph4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ph4.setIcon(icon4);
        ph4.setText(books[13]);
        ph4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ph4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ph4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ph4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ph4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ph4MouseClicked(evt);
            }
        });

        ph3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ph3.setIcon(icon3);
        ph3.setText(books[12]);
        ph3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ph3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ph3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ph3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ph3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ph3MouseClicked(evt);
            }
        });

        ph7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ph7.setIcon(icon7);
        ph7.setText(books[16]);
        ph7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ph7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ph7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ph7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ph7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ph7MouseClicked(evt);
            }
        });

        ph9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ph9.setIcon(icon9);
        ph9.setText(books[18]);
        ph9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ph9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ph9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ph9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ph9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ph9MouseClicked(evt);
            }
        });

        ph8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ph8.setIcon(icon8);
        ph8.setText(books[17]);
        ph8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ph8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ph8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ph8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ph8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ph8MouseClicked(evt);
            }
        });

        ph6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ph6.setIcon(icon6);
        ph6.setText(books[15]);
        ph6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ph6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ph6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ph6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ph6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ph6MouseClicked(evt);
            }
        });

        ph5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ph5.setIcon(icon5);
        ph5.setText(books[14]);
        ph5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ph5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ph5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ph5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ph5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ph5MouseClicked(evt);
            }
        });

        ph10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ph10.setIcon(icon10);
        ph10.setText(books[19]);
        ph10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ph10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ph10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ph10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ph10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ph10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ph1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ph2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ph3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ph4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(ph6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ph7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ph8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ph9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ph10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ph5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(131, 131, 131))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ph4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ph3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ph2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ph1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ph7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ph8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ph6, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ph9, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ph5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ph10, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(149, 149, 149))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ph9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ph9MouseClicked
        
    }//GEN-LAST:event_ph9MouseClicked

    private void ph1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ph1MouseClicked
        
    }//GEN-LAST:event_ph1MouseClicked

    private void ph2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ph2MouseClicked
        
    }//GEN-LAST:event_ph2MouseClicked

    private void ph3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ph3MouseClicked
        
    }//GEN-LAST:event_ph3MouseClicked

    private void ph4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ph4MouseClicked
        
    }//GEN-LAST:event_ph4MouseClicked

    private void ph5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ph5MouseClicked
        
    }//GEN-LAST:event_ph5MouseClicked

    private void ph6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ph6MouseClicked
        
    }//GEN-LAST:event_ph6MouseClicked

    private void ph7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ph7MouseClicked
        
    }//GEN-LAST:event_ph7MouseClicked

    private void ph8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ph8MouseClicked
        
    }//GEN-LAST:event_ph8MouseClicked

    private void ph10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ph10MouseClicked
        
    }//GEN-LAST:event_ph10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, SQLException, IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IyiPopulerYeni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IyiPopulerYeni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IyiPopulerYeni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IyiPopulerYeni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IyiPopulerYeni().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel ph1;
    private static javax.swing.JLabel ph10;
    private static javax.swing.JLabel ph2;
    private static javax.swing.JLabel ph3;
    private static javax.swing.JLabel ph4;
    private static javax.swing.JLabel ph5;
    private static javax.swing.JLabel ph6;
    private static javax.swing.JLabel ph7;
    private static javax.swing.JLabel ph8;
    private static javax.swing.JLabel ph9;
    // End of variables declaration//GEN-END:variables
}
